In [1]:
import os
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [2]:
names = os.listdir('./전라남도')

In [4]:
names = [name[:-4] for name in names]

In [7]:
df_전라남도 = pd.DataFrame()

for name in names:
    df = pd.read_csv(f'./전라남도/{name}.csv',encoding='ANSI')
    df_전라남도 = pd.concat([df_전라남도,df],ignore_index=True)

In [8]:
df_전라남도

       기준년월 기초지자체      방문자 구분     방문자 수
0    202301   강진군   외지인방문자(b)  354405.0
1    202301   강진군   외국인방문자(c)    1467.0
2    202302   강진군   외지인방문자(b)  249630.0
3    202302   강진군   외국인방문자(c)    1622.0
4    202303   강진군   외지인방문자(b)  292136.0
..      ...   ...         ...       ...
787  202308   화순군  외부방문자(b+c)  776062.0
788  202309   화순군  외부방문자(b+c)  777295.0
789  202310   화순군  외부방문자(b+c)  799373.0
790  202311   화순군  외부방문자(b+c)  629807.0
791  202312   화순군  외부방문자(b+c)  581582.0

[792 rows x 4 columns]

In [9]:
df_전라남도.groupby('기초지자체')[['방문자 수']].sum().sort_values(by='방문자 수',ascending=False)

            방문자 수
기초지자체
여수시    47164782.0
순천시    36600062.0
목포시    28422458.0
나주시    20523881.0
담양군    20424327.0
광양시    18966700.0
무안군    16932954.0
화순군    16784456.0
장성군    12323902.0
고흥군    12263392.0
해남군    12134934.0
영암군    11661437.0
영광군    10582602.0
신안군    10486373.0
보성군    10171620.0
구례군     9479514.0
완도군     9192096.0
함평군     8288860.0
곡성군     7999136.0
진도군     7971774.0
강진군     7789338.0
장흥군     7066732.0